import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

// By default build main.js into the project dir (what CI/releases need).
// For local dev, set YASINC_VAULT to the installed-plugin folder and the
// build lands straight in the Obsidian vault, e.g.
//   YASINC_VAULT=D:/Obsidian/mrrepac/.obsidian/plugins/yasinc
const vault = process.env.YASINC_VAULT;
const outfile = vault ? `${vault}/main.js` : "main.js";

const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", ...builtinModules],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile,
};

if (prod) {
  await esbuild.build(buildOptions);
} else {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
}
